### ISSUE TITLE
Release 1 review

### ISSUE THREAD

**Issue by theaspect** [RuiFoxx/ProgramEngineering#1]
1. Перед тем как делать релиз, необходимо убедиться что приложение компилируется
2. Форматирование кода не соответствует стандарту http://www.oracle.com/technetwork/java/codeconvtoc-136057.html
3. Вместо
   `
   if(){
   }else{
       if(){
       }else{
       }
   }
   `
   Пишите так:
   `
   if(){
   }else if(){
   }else{
   }
   `
4. В коде не должно быть закомментированных фрагментов без причины почему этот код ен удален, у вас вся история в гите, зачем засорять код https://github.com/RuiFoxx/ProgramEngineering/blob/master/src/com/Check.java#L113
5. Непонятно что тут происходит, добавьте комментарии https://github.com/RuiFoxx/ProgramEngineering/blob/master/src/com/Check.java#L78
   Для парсинга даты можно перевести парсер в строгий режим http://docs.oracle.com/javase/7/docs/api/java/text/DateFormat.html#setLenient(boolean)
6. Если у вас набор полей фиксированный то вместо HashMap лучше создать специальный класс из 7 или 8 полей и заполнять его https://github.com/RuiFoxx/ProgramEngineering/blob/master/src/com/Cli.java#L11
7. Ненужный import https://github.com/RuiFoxx/ProgramEngineering/blob/master/src/com/Main.java#L3
8. Этот фрагмент точно нужен? https://github.com/RuiFoxx/ProgramEngineering/blob/master/src/com/Cli.java#L22-L37
9. Вместо такого
   `
       posixOptions.addOption(loginOption); //добавляем опции для последующего парсинга
       posixOptions.addOption(passOption);
   `
   лучше использовать fluent запись:
   `
   posixOptions
       .addOption(new Option("l", "login", true, " your login"))
       .addOption(new Option("p", "password", true, " your password"));
   `
10. Posix парсер устарел, используйте DefaultParser https://github.com/RuiFoxx/ProgramEngineering/blob/master/src/com/Cli.java#L49
11. Если вызвать метод help() у класса до того как будет вызван parse() то справка не будет выведена, каждый вызов parse() будет переинициализировать класс https://github.com/RuiFoxx/ProgramEngineering/blob/master/src/com/Cli.java#L74

**Comment by RuiFoxx** [comment]
1.1, 1.7-1.10 fixed

**Comment by AgentP217** [comment]
Fixed 1.2-1.6

**Comment by RuiFoxx** [comment]
1.11 fixed.
