### ISSUE TITLE
Return "Wrong role", but role is correct

### ISSUE THREAD

**Issue by DaffPunks** [RuiFoxx/ProgramEngineering#2]
https://github.com/RuiFoxx/ProgramEngineering/blob/master/src/com/Check.java#L74
![image](https://cloud.githubusercontent.com/assets/15698578/19194460/d1cf2a56-8cd7-11e6-8823-ec403ff84414.png)
При отсутствии доступа к ресурсу, но с правильной ролью вываливается Exit.code(3)

**Comment by RuiFoxx** [comment]
jdoe имеет доступ к обоим ресурсам, закрыто.
