### ISSUE TITLE
Review 1.2

### ISSUE THREAD

**Issue by theaspect** [RuiFoxx/ProgramEngineering#5]
1. https://github.com/RuiFoxx/ProgramEngineering/blob/master/src/com/Check.java#L99 устаревшие методы
2. везде где это возможно используй for-each вместо итерации по индексу https://github.com/RuiFoxx/ProgramEngineering/blob/master/src/com/Check.java#L15 
   https://github.com/RuiFoxx/ProgramEngineering/blob/master/src/com/Check.java#L36 повсеместно короче
3. то что внутри if-ов должно быть перенесено в методы класса CmdUser и названы примерно isAuthentication isAuthorization isAccounting https://github.com/RuiFoxx/ProgramEngineering/blob/master/src/com/Cli.java#L57-L74
   Переверни порядок на обратный и используй if{}else if{}else{}
4. почему параметры static? https://github.com/RuiFoxx/ProgramEngineering/blob/master/src/com/Cli.java#L9-L13
5. зачем нужна инициализация? https://github.com/RuiFoxx/ProgramEngineering/blob/master/src/com/Hash.java#L10-L11
6. почему метод статический? https://github.com/RuiFoxx/ProgramEngineering/blob/master/src/com/Cli.java#L26
7. Пункт 6.1 java coding conventions рекомендует каждое поле объявлять на отдельной строке https://github.com/RuiFoxx/ProgramEngineering/blob/master/src/com/Role.java#L6
8. Непонятно что тут делается (пункт 5 из прошлого Issue) https://github.com/RuiFoxx/ProgramEngineering/blob/master/src/com/Check.java#L110
   нужен подробный комментарий (скорее всего тебе нужен simpleDateFormat.setLenient(false))

**Comment by RuiFoxx** [comment]
Fixed 6.

**Comment by RuiFoxx** [comment]
Fixed 5, 7.

**Comment by RuiFoxx** [comment]
Насчёт 4: параметры static, так как мы используем методы, содержащие эти поля, в классе Check без создания объекта. Т.е. и геттеры static, и, соответственно, поля тоже.

**Comment by AgentP217** [comment]
Fixed 1, 3

**Comment by AgentP217** [comment]
Fixed 8

**Comment by RuiFoxx** [comment]
Fixed 2.
